IctuTaekwondo.WebClient/Components/HeaderViewComponent.cs
using IctuTaekwondo.Shared;
using IctuTaekwondo.Shared.Services.Account;
using Microsoft.AspNetCore.Mvc;

namespace IctuTaekwondo.WebClient.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IAccountService accountService;

        public HeaderViewComponent(IAccountService authService)
        {
            accountService = authService;
        }

        public IViewComponentResult Invoke()
        {
            if (User?.Identity?.IsAuthenticated == false) return View("LoggedOutNavButton");
            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];
            var user = accountService.GetUser(token).Result;
            if (user == null) return View("LoggedOutNavButton");

            return View("LoggedInNavButton", user);
        }
    }
}

IctuTaekwondo.WebClient/Components/ModalViewComponent.cs
using IctuTaekwondo.WebClient.Models;
using Microsoft.AspNetCore.Mvc;

namespace IctuTaekwondo.WebClient.Components
{
    public class ModalViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ModalViewModel model)
        {
            return View(model);
        }
    }
}

IctuTaekwondo.WebClient/Components/SidebarViewComponent.cs
using IctuTaekwondo.Shared;
using IctuTaekwondo.Shared.Services.Account;
using Microsoft.AspNetCore.Mvc;

namespace IctuTaekwondo.WebClient.Components
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly IAccountService _accountService;

        public SidebarViewComponent(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public IViewComponentResult Invoke()
        {
            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];
            var user = _accountService.GetProfileAsync(token).Result;
            return View(user);
        }
    }
}

IctuTaekwondo.WebClient/Controllers/AuthController.cs
using System.Net;
using Htmx;
using IctuTaekwondo.Shared;
using IctuTaekwondo.Shared.Responses.Auth;
using IctuTaekwondo.Shared.Schemas.Auth;
using IctuTaekwondo.Shared.Services.Auth;
using IctuTaekwondo.Shared.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace IctuTaekwondo.WebClient.Controllers
{
    public class AuthController : Controller
    {
        private readonly IApiService apiService;
        private readonly string[] allowedRedirectUrl =
        [
            "/accounts",
            "/auth/register",
        ];

        public AuthController(IApiService apiService)
        {
            this.apiService = apiService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginSchema schema)
        {
            if (!ModelState.IsValid) return View(schema);

            try
            {
                var response = await apiService.PostAsync<JwtResponse>("api/auth/login", schema.ToStringContent());
                if (response.StatusCode != HttpStatusCode.OK)
                {
                    foreach (var (key, value) in response.Errors)
                    {
                        var keyName = string.Empty;

                        if (key.Contains("Email") || key.Contains("UserName")) keyName = "Email";
                        if (key.Contains("Password")) keyName = "ConfirmPassword";

                        foreach (var error in value)
                        {
                            ModelState.AddModelError(keyName, error);
                        }
                    }
                }

                var jwt = response.Data;

                if (jwt == null)
                {
                    ModelState.AddModelError(string.Empty, "Đăng nhập không thành công.\nTài khoản hoặc mật khảu không chính xác");
                    return View(schema);
                }

                if (Request.Cookies.ContainsKey(GlobalConst.CookieAuthTokenKey))
                {
                    Response.Cookies.Delete(GlobalConst.CookieAuthTokenKey);
                }

                var cookieOptions = new CookieOptions
                {
                    HttpOnly = true,
                    //Secure = true,
                    Expires = schema.RememberMe ? jwt.ExpiredAt : null,
                    SameSite = SameSiteMode.Strict
                };

                Response.Cookies.Append(GlobalConst.CookieAuthTokenKey, jwt.Token, cookieOptions);

                return RedirectToAction("Profile", "Account");
            }
            catch (HttpRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ModelState.AddModelError(string.Empty, ex.InnerException?.Message ?? string.Empty);
                return View(schema);
            }
        }

        [HttpGet]
        [Authorize]
        public IActionResult Logout()
        {
            if (Request.Cookies.ContainsKey(GlobalConst.CookieAuthTokenKey))
            {
                Response.Cookies.Delete(GlobalConst.CookieAuthTokenKey);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

IctuTaekwondo.WebClient/Controllers/DashboardController.cs
using System.Configuration;
using IctuTaekwondo.Shared;
using IctuTaekwondo.Shared.Enums;
using IctuTaekwondo.Shared.Services.Finances;
using IctuTaekwondo.Shared.Utils;
using IctuTaekwondo.WebClient.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IctuTaekwondo.WebClient.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IFinancesService financesService;
        private readonly IConfiguration configuration;

        public DashboardController(IFinancesService financesService, IConfiguration configuration)
        {
            this.financesService = financesService;
            this.configuration = configuration;
        }

        [Authorize]
        public async Task<IActionResult> Index([FromQuery] ReportRange? range = null)
        {
            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];

            var model = new DashboardViewModel();
            var apiUrl = configuration["ApiUrl"];

            if (!string.IsNullOrEmpty(apiUrl))
                model.ApiUrl = apiUrl;

            if (range.HasValue)
            {
                (DateTime StartDate, DateTime EndDate) current;
                (DateTime StartDate, DateTime EndDate) pass;
                current = ReportHelper.GetCurrentDates(range.Value);
                pass = ReportHelper.GetPastPeriodDates(range.Value);
                var currentReport = await financesService.GetReportAsync(token, current.StartDate,current.EndDate);
                var passReport = await financesService.GetReportAsync(token, pass.StartDate, pass.EndDate);
                model.Current = currentReport;
                model.Pass = passReport;
                model.Range = range.Value;
                return View(model);
            }

            var report = await financesService.GetReportAsync(token, null, null);
            model.Current = report;

            return View(model);
        }
    }
}

IctuTaekwondo.WebClient/Views/Shared/Components/Header/LoggedInNavButton.cshtml
@using IctuTaekwondo.Shared.Responses.User
@model UserResponse
@{
	ArgumentNullException.ThrowIfNull(Model);
}

<div class="flex items-center">
	<div class="ms-3 flex items-center">
		<div>
			<button type="button" class="flex rounded-full bg-gray-800 text-sm focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" aria-expanded="false" data-dropdown-toggle="dropdown-user">
				<span class="sr-only">Open user menu</span>
				@if (!string.IsNullOrEmpty(Model.AvatarUrl))
				{
					<div class="size-8 overflow-hidden rounded-full">
						<img class="h-full w-full object-cover" src="@Model.AvatarUrl" alt="avatar" />
					</div>
				}
				else
				{
					<div class="relative size-8 overflow-hidden rounded-full bg-gray-100 dark:bg-gray-600">
						<svg class="absolute -left-1 h-10 w-10 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
					</div>
				}
			</button>
		</div>
		<div class="z-50 my-4 hidden list-none divide-y divide-gray-100 rounded bg-white text-base shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown-user">
			<div class="px-4 py-3" role="none">
				<p class="text-sm text-gray-900 dark:text-white" role="none">
					@Model.FullName
				</p>
				<p class="truncate text-sm font-medium text-gray-900 dark:text-gray-300" role="none">
					@Model.Email
				</p>
			</div>
			<ul class="py-1" role="none">
				<li>
					<a asp-controller="Dashboard" asp-action="Index" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Bảng điều khiển</a>
				</li>
				<li>
					<a asp-controller="Account" asp-action="Profile" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Tài khoản</a>
				</li>
				<li>
					<a asp-controller="Auth" asp-action="Logout" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Đăng xuất</a>
				</li>
			</ul>
		</div>
	</div>
</div>

IctuTaekwondo.WebClient/Views/Shared/Components/Header/LoggedOutNavButton.cshtml
<div class="flex gap-2">
	<a asp-controller="Auth" asp-action="Login" class="rounded-lg bg-blue-700 px-2.5 py-1.5 text-sm font-medium text-white hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 focus:outline-none dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
		Đăng nhập
	</a>
</div>