IctuTaekwondo.WebClient/Controllers/FinancesController.cs
using Htmx;
using IctuTaekwondo.Shared;
using IctuTaekwondo.Shared.Schemas.Finance;
using IctuTaekwondo.Shared.Services.Finances;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IctuTaekwondo.WebClient.Controllers
{
    public class FinancesController : Controller
    {
        private readonly IFinancesService _service;

        public FinancesController(IFinancesService service)
        {
            _service = service;
        }

        private readonly List<string> validUrls = ["/Finances"];

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index([FromQuery] int page = 1, [FromQuery] int size = 10)
        {
            ViewData["QueryParameters"] = Request.Query;

            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];
            var list = await _service.GetAllAsync(token, page, size);

            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Detail(int id, [FromQuery] int page = 1, [FromQuery] int size = 10)
        {
            ViewData["QueryParameters"] = Request.Query;

            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];

            var detail = await _service.FindByIdAsync(token, id);
            if (detail == null) return NotFound();
            ViewData["CurrentFinance"] = detail;

            return View(new FinanceUpdateSchema
            {
                Id = detail.Id,
                Type = detail.Type,
                Category = detail.Category,
                Amount = detail.Amount,
                TransactionDate = detail.TransactionDate,
                Description = detail.Description,
            });
        }

        [HttpPut]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id, FinanceUpdateSchema schema)
        {
            if (!Request.IsHtmx()) return BadRequest();

            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];

            if (ModelState.IsValid)
            {
                var @new = await _service.UpdateAsync(token, id, schema);
                if (@new != null)
                {
                    Response.Htmx(h => h.WithTrigger("add-sweetalert2-toast", new
                    {
                        icon = "success",
                        title = "Cập nhật giao dịch thành công",
                    }));

                    return PartialView("_UpdateFinanceFormPartial", new FinanceUpdateSchema
                    {
                        Id = @new.Id,
                        Type = @new.Type,
                        Category = @new.Category,
                        Amount = @new.Amount,
                        TransactionDate = @new.TransactionDate,
                        Description = @new.Description
                    });
                }
            }

            Response.Htmx(h => h.WithTrigger("add-sweetalert2-toast", new
            {
                icon = "error",
                title = "Cập nhật giao dịch không thành công",
            }));

            return PartialView("_UpdateFinanceFormPartial", schema);
        }

        [HttpDelete]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id, [FromQuery] string? next)
        {
            if (!Request.IsHtmx()) return BadRequest();

            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];

            if (ModelState.IsValid)
            {
                var isSuccess = await _service.DeleteAsync(token, id);
                if (isSuccess)
                {
                    object? toast = toast = new
                    {
                        icon = "success",
                        title = "Xoá giao dịch thành công",
                    };

                    if (!string.IsNullOrEmpty(next) && validUrls.Contains(next))
                        toast = new
                        {
                            icon = "success",
                            title = "Xoá giao dịch thành công",
                            redirectUrl = next
                        };

                    Response
                        .Htmx(h => h
                        .WithTrigger("add-sweetalert2-toast", toast)
                        .WithTrigger("delete-elm", $"Row-{id}"));

                    return NoContent();
                }
            }

            Response.Htmx(h => h.WithTrigger("add-sweetalert2-toast", new
            {
                icon = "error",
                title = "Xoá giao dịch không thành công",
            }));

            return NoContent();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([FromForm] FinanceCreateSchema schema)
        {
            if (!Request.IsHtmx()) return BadRequest();

            var token = Request.Cookies[GlobalConst.CookieAuthTokenKey];

            if (ModelState.IsValid)
            {
                var newUser = await _service.CreateAsync(token, schema);
                if (newUser != null)
                {
                    Response.Htmx(h => h.WithTrigger("add-sweetalert2-toast", new
                    {
                        icon = "success",
                        title = "Tạo giao dịch thành công",
                    }));
                    return PartialView("_CreateFinanceFormPartial", new FinanceCreateSchema());
                }
            }
            return PartialView("_CreateFinanceFormPartial", schema);
        }

    }
}

IctuTaekwondo.WebClient/Views/Finances/Detail.cshtml
@using IctuTaekwondo.Shared.Enums
@using IctuTaekwondo.Shared.Responses
@using IctuTaekwondo.Shared.Responses.Finance
@using IctuTaekwondo.Shared.Responses.User
@using IctuTaekwondo.Shared.Schemas.Finance
@model FinanceUpdateSchema
@{
	ViewData["Title"] = "Thông tin giao dịch";
	Layout = "_DashboardLayout";
}

<section class="bg-white py-4 antialiased dark:bg-gray-900">
	<div class="mx-auto max-w-screen-lg">

		<!-- Breadcrumb -->
		<nav class="mb-4 flex" aria-label="Breadcrumb">
			<ol class="inline-flex items-center space-x-1 rtl:space-x-reverse md:space-x-2">
				<li class="inline-flex items-center">
					<a href="/" class="inline-flex items-center text-sm font-medium text-gray-700 hover:underline hover:text-primary-600 dark:text-gray-400 dark:hover:text-white">
						<svg class="me-2 h-4 w-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
							<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m4 12 8-8 8 8M6 10.5V19a1 1 0 0 0 1 1h3v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h3a1 1 0 0 0 1-1v-8.5" />
						</svg>
						Trang chủ
					</a>
				</li>
				<li>
					<div class="flex items-center">
						<svg class="mx-1 h-4 w-4 text-gray-400 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
							<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 5 7 7-7 7" />
						</svg>
						<a asp-controller="Finances" asp-action="Index" class="ms-1 text-sm font-medium text-gray-700 hover:underline hover:text-primary-600 dark:text-gray-400 md:ms-2 dark:hover:text-white">
							Quản lý thu chi
						</a>
					</div>
				</li>
				<li aria-current="page">
					<div class="flex items-center">
						<svg class="mx-1 h-4 w-4 text-gray-400 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
							<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 5 7 7-7 7" />
						</svg>
						<span class="ms-1 text-sm font-medium text-gray-500 dark:text-gray-400 md:ms-2">@Model.Id</span>
					</div>
				</li>
			</ol>
		</nav>

		<h2 class="border-b border-gray-200 pb-4 text-xl font-semibold text-gray-900 dark:text-white dark:border-gray-700 sm:text-2xl">
			Thông tin giao dịch
		</h2>

		<div class="grid-cols-1 grid gap-3 pt-6 lg:grid-cols-8">
			<div id="Message-Update-Finance" class="col-span-1 lg:col-span-5" hidden></div>

			<!-- Action Buttons -->
			<div class="col-span-1 lg:col-span-2 lg:order-2">
				<h6 class="mb-2 block text-sm font-medium text-gray-900 dark:text-white">Hành động</h6>

				<div class="flex gap-2 gap-x-2 gap-y-4 lg:flex-col">
						<button _="on click trigger 'Update-Finance'"
								id="Update-Finance-Submit"
								class="inline-flex w-fit items-center justify-center rounded-lg bg-primary-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300 disabled:cursor-not-allowed disabled:bg-primary-500 dark:bg-primary-600 lg:w-full dark:hover:bg-primary-700 dark:focus:ring-primary-800">
							<svg id="Update-Finance-Indicator" aria-hidden="true" role="status" class="hx-btn-indicator me-3 h-4 w-4 animate-spin text-white" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="#E5E7EB" />
								<path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentColor" />
							</svg>
							Lưu thay đổi
						</button>
						<button _="on htmx:beforeRequest set me.disabled to true end on htmx:afterRequest set me.disabled to false"
								hx-delete
								hx-action="Delete"
								hx-route-id="@Model.Id"
								hx-route-next="/Finances"
								hx-target="#toast-list"
								hx-swap="beforeend"
								hx-confirm="Thành tích này sẽ bị xoá vĩnh viễn."
								class="inline-flex w-fit items-center justify-center rounded-lg bg-red-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 disabled:cursor-not-allowed disabled:bg-red-500 lg:w-full">
							<svg aria-hidden="true" role="status" class="hx-btn-indicator me-3 h-4 w-4 animate-spin text-white" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="#E5E7EB" />
								<path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentColor" />
							</svg>
							Xoá giao dịch
						</button>
				</div>
			</div>

			<!-- Information -->
			@await Html.PartialAsync("_UpdateFinanceFormPartial", Model)
		</div>
	</div>
</section>

IctuTaekwondo.WebClient/Views/Finances/Index.cshtml
@using IctuTaekwondo.Shared.Enums
@using IctuTaekwondo.Shared.Responses
@using IctuTaekwondo.Shared.Responses.Finance
@using IctuTaekwondo.Shared.Schemas.Finance
@using Microsoft.AspNetCore.WebUtilities

@model Paginator<FinanceResponse>
@{
	ViewData["Title"] = "Quản lý thu chi";
	Layout = "_DashboardLayout";

	var queryParameters = (IQueryCollection)ViewData["QueryParameters"]!;
	var queryDict = queryParameters.ToDictionary(q => q.Key, q => q.Value.ToString());

	ArgumentNullException.ThrowIfNull(Model);
}

<section class="bg-white py-4 antialiased dark:bg-gray-900">
	<div class="mx-auto max-w-screen-lg px-4">

		<nav class="mb-4 flex" aria-label="Breadcrumb">
			<ol class="inline-flex items-center space-x-1 rtl:space-x-reverse md:space-x-2">
				<li class="inline-flex items-center">
					<a href="/" class="inline-flex items-center text-sm font-medium text-gray-700 hover:underline hover:text-primary-600 dark:text-gray-400 dark:hover:text-white">
						<svg class="me-2 h-4 w-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
							<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m4 12 8-8 8 8M6 10.5V19a1 1 0 0 0 1 1h3v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h3a1 1 0 0 0 1-1v-8.5" />
						</svg>
						Trang chủ
					</a>
				</li>
				<li>
					<div class="flex items-center">
						<svg class="mx-1 h-4 w-4 text-gray-400 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
							<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 5 7 7-7 7" />
						</svg>
						<a asp-controller="Finances" asp-action="Index" class="ms-1 text-sm font-medium text-gray-700 hover:underline hover:text-primary-600 dark:text-gray-400 md:ms-2 dark:hover:text-white">
							Quản lý thu chi
						</a>
					</div>
				</li>
				<li aria-current="page">
					<div class="flex items-center">
						<svg class="mx-1 h-4 w-4 text-gray-400 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
							<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 5 7 7-7 7" />
						</svg>
						<span class="ms-1 text-sm font-medium text-gray-500 dark:text-gray-400 md:ms-2">Danh sách giao dịch</span>
					</div>
				</li>
			</ol>
		</nav>

		<h2 class="border-b border-gray-200 pb-4 text-xl font-semibold text-gray-900 dark:text-white dark:border-gray-700 sm:text-2xl">
			Quản lý thu chi
		</h2>

		<div class="pt-6">
			<div class="relative border bg-white shadow-md dark:border-gray-700 dark:bg-gray-800 sm:rounded-lg">
				<div class="flex flex-col space-y-3 px-4 py-3 lg:flex-row lg:items-center lg:justify-between lg:space-y-0 lg:space-x-4">
					<div class="flex w-full gap-3 md:w-1/2">
						<form asp-all-route-data="queryDict" method="get" class="flex w-full items-center">
							<div class="relative w-full">
								<div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
									<svg aria-hidden="true" class="h-5 w-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
									</svg>
								</div>
								<input value="@queryParameters["search"]" name="search" type="text" id="search" class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2 pl-10 text-sm text-gray-900 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Tìm kiếm" required="">
							</div>
						</form>

						@if (queryParameters["search"].Any())
						{
							<a asp-action="Index" class="flex w-full items-center justify-center rounded-lg border border-gray-200 bg-white p-2 text-sm font-medium text-gray-900 hover:bg-gray-100 hover:text-primary-700 focus:outline-none focus:z-10 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 md:w-auto dark:focus:ring-gray-700 dark:hover:text-white dark:hover:bg-gray-700" type="button">
								<svg class="size-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
									<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18 17.94 6M18 18 6.06 6" />
								</svg>
							</a>
						}
					</div>

					<div class="flex-shrink-0 flex flex-col space-y-3 md:flex-row md:items-center md:space-y-0 md:space-x-3 lg:justify-end">
						<button data-modal-target="Modal-Create-Finance"
								data-modal-toggle="Modal-Create-Finance"
								class="flex items-center justify-center rounded-lg bg-primary-700 p-2 text-sm font-medium text-white hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 focus:outline-none dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
							<svg class="size-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
								<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14m-7 7V5" />
							</svg>
						</button>
						<button id="order-dropdown-button" data-dropdown-toggle="order-dropdown" class="flex w-full items-center justify-center rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-100 hover:text-primary-700 focus:outline-none focus:z-10 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 md:w-auto dark:focus:ring-gray-700 dark:hover:text-white dark:hover:bg-gray-700" type="button">
							<svg class="-ml-1 mr-1.5 size-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
								<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 20V10m0 10-3-3m3 3 3-3m5-13v10m0-10 3 3m-3-3-3 3" />
							</svg>
							Sắp xếp
						</button>
						<div id="order-dropdown" class="z-10 hidden w-fit divide-y divide-gray-100 rounded bg-white shadow dark:bg-gray-700 dark:divide-gray-600">
							<div class="py-1">
								<a asp-all-route-data="queryDict" asp-route-order="-CreatedAt" class="block w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-white">
									Theo ngày tạo mới nhất
								</a>
								<a asp-all-route-data="queryDict" asp-route-order="CreatedAt" class="block w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-white">
									Theo ngày tạo cũ nhất
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="overflow-x-auto">
					<table class="w-full text-left text-sm text-gray-500 dark:text-gray-400">
						<thead class="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400">
							<tr>
								<th scope="col" class="p-4">
									<div class="flex items-center">
										<input id="checkbox-all" type="checkbox" class="h-4 w-4 rounded border-gray-300 bg-gray-100 text-primary-600 focus:ring-primary-500 focus:ring-2 dark:ring-offset-gray-800 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600">
										<label for="checkbox-all" class="sr-only">checkbox</label>
									</div>
								</th>
								<th scope="col" class="whitespace-nowrap px-4 py-3">Danh mục</th>
								<th scope="col" class="whitespace-nowrap px-4 py-3">Loại</th>
								<th scope="col" class="whitespace-nowrap px-4 py-3">Số tiền</th>
								<th scope="col" class="whitespace-nowrap px-4 py-3">Ngày giao dịch</th>
								<th scope="col" class="px-4 py-3">
									<span class="sr-only">Actions</span>
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model.Items)
							{
								<tr id="Row-@item.Id" class="border-b hover:bg-gray-100 dark:border-gray-600 dark:hover:bg-gray-700">
									<td class="w-4 px-4 py-3">
										<div class="flex items-center">
											<input id="checkbox-table-@item.Id" value="@item.Id" table-checkbox type="checkbox" onclick="event.stopPropagation()" class="h-4 w-4 rounded border-gray-300 bg-gray-100 text-primary-600 focus:ring-primary-500 focus:ring-2 dark:ring-offset-gray-800 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600">
											<label for="checkbox-table-@item.Id" class="sr-only">checkbox</label>
										</div>
									</td>

									<td class="whitespace-nowrap px-4 py-2 text-gray-900 dark:text-white">
										<a asp-action="Detail" asp-route-id="@item.Id" class="font-bold hover:underline">@item.Category</a>
									</td>
									<td class="whitespace-nowrap px-4 py-2 text-gray-900 dark:text-white">
										@item.Type.GetDisplayName()
									</td>
									<td class="whitespace-nowrap px-4 py-2 text-gray-900 dark:text-white">
										@if (item.Type == TransactionType.Expense)
										{
											<span class="rounded-sm bg-red-100 px-2.5 py-0.5 font-medium text-red-800 dark:bg-red-900 dark:text-red-300">
												-@(item.Amount.ToString("N0"))đ
											</span>
										}
										else
										{
											<span class="rounded-sm bg-green-100 px-2.5 py-0.5 font-medium text-green-800 dark:bg-green-900 dark:text-green-300">
												+@(item.Amount.ToString("N0"))đ
											</span>
										}
									</td>
									<td class="whitespace-nowrap px-4 py-2 text-gray-900 dark:text-white">
										@item.TransactionDate.ToString("dd/MM/yyyy HH:mm")
									</td>
									<td class="whitespace-nowrap px-4 py-2 text-gray-900 dark:text-white">
										<div class="flex items-center justify-end">
											<button _="on htmx:beforeRequest set me.disabled to true end
													   on htmx:afterRequest set me.disabled to false"
													hx-delete
													hx-action="Delete"
													hx-route-id="@item.Id"
													hx-confirm="Thành tích này sẽ bị xoá vĩnh viễn."
													type="button"
													class="inline-flex items-center rounded-full p-2 text-center text-sm font-medium text-red-600 hover:bg-red-500 hover:text-white focus:ring-4 focus:outline-none focus:ring-red-300">
												<svg class="size-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
													<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z" />
												</svg>
											</button>
										</div>
									</td>
								</tr>
							}
						</tbody>
					</table>

					<script>
						$(document).ready(function() {
							$('#checkbox-all').click(function() {
								$('input[table-checkbox]').prop('checked', this.checked);
							});
						});
					</script>
				</div>

				<!-- Table Footer -->
				@await Html.PartialAsync("Partials/_TableFooterPartial", new TableFooterViewModel
{
	CurrentPage = Model.CurrentPage,
	PageSize = Model.PageSize,
	PageCount = Model.PageCount,
	TotalItemCount = Model.TotalItemCount,
	CurrentItemCount = Model.Items.Count,
	HasPrevious = Model.HasPrevious,
	HasNext = Model.HasNext,
	ItemRange = Model.GetItemRange(),
	DisplayPageRange = Model.GetDisplayPageRange(),
})
			</div>
		</div>
	</div>
</section>

@section Modals
{
	@await Html.PartialAsync("Partials/_ModalPartial", new ModalViewModel
{
	Id = "Create-Finance",
	Header = "Tạo giao dịch mới",
	BodyPartialName = "_CreateFinanceFormPartial",
	BodyModel = new FinanceCreateSchema()
})
}